name: Deploy HTML Page

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy HTML file
        run: |
          mkdir public
          cp index.html public/
        # Upload the HTML file to GitHub Pages
        # Make sure to replace <username> with your GitHub username
        - name: Deploy to GitHub Pages
        uses: PrathameshLohar/github-pages-deploy-action@4.1.4
        with:
          ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: public
