name: Run Hello World Streamlit App

on:
  push:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.12.2
        uses: actions/setup-python@v3
        with:
          python-version: '3.12.2' # Update if needed for newer versions

      - name: Install dependencies
        run: pip install streamlit

      - name: Run the Streamlit app
        run: streamlit run app.py
